"""
Static S&P 500 constituent list (ticker, company name, GICS sector).

Why static instead of fetched: FMP deprecated their `/sp500-constituent` endpoint for
anyone without a legacy subscription predating August 2025 — it now 403s on a standard
API key (confirmed directly against the live API while building this). Index membership
changes only a handful of times a year, so a periodically-refreshed static list is a
reasonable trade for not needing a paid FMP tier just to enumerate the universe.

This is a curated subset (~180 of the largest, most liquid S&P 500 constituents spanning
all 11 GICS sectors) rather than a claimed-complete 503-ticker list — accuracy of a full
list typed from memory can't be guaranteed, and a partial-but-correct universe is more
useful than a complete-but-wrong one for a screener. To expand toward full coverage,
either upgrade the FMP plan and swap this out for a live constituent call, or extend this
list by hand from a public source (e.g. Wikipedia's "List of S&P 500 companies").
"""

SP500_UNIVERSE: list[dict[str, str]] = [
    # Technology
    {"symbol": "AAPL", "name": "Apple Inc.", "sector": "Technology"},
    {"symbol": "MSFT", "name": "Microsoft Corporation", "sector": "Technology"},
    {"symbol": "NVDA", "name": "NVIDIA Corporation", "sector": "Technology"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "sector": "Technology"},
    {"symbol": "ORCL", "name": "Oracle Corporation", "sector": "Technology"},
    {"symbol": "CRM", "name": "Salesforce, Inc.", "sector": "Technology"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "sector": "Technology"},
    {"symbol": "AMD", "name": "Advanced Micro Devices, Inc.", "sector": "Technology"},
    {"symbol": "CSCO", "name": "Cisco Systems, Inc.", "sector": "Technology"},
    {"symbol": "ACN", "name": "Accenture plc", "sector": "Technology"},
    {"symbol": "IBM", "name": "International Business Machines Corporation", "sector": "Technology"},
    {"symbol": "INTC", "name": "Intel Corporation", "sector": "Technology"},
    {"symbol": "TXN", "name": "Texas Instruments Incorporated", "sector": "Technology"},
    {"symbol": "QCOM", "name": "QUALCOMM Incorporated", "sector": "Technology"},
    {"symbol": "AMAT", "name": "Applied Materials, Inc.", "sector": "Technology"},
    {"symbol": "MU", "name": "Micron Technology, Inc.", "sector": "Technology"},
    {"symbol": "LRCX", "name": "Lam Research Corporation", "sector": "Technology"},
    {"symbol": "ADI", "name": "Analog Devices, Inc.", "sector": "Technology"},
    {"symbol": "KLAC", "name": "KLA Corporation", "sector": "Technology"},
    {"symbol": "PANW", "name": "Palo Alto Networks, Inc.", "sector": "Technology"},
    {"symbol": "SNPS", "name": "Synopsys, Inc.", "sector": "Technology"},
    {"symbol": "CDNS", "name": "Cadence Design Systems, Inc.", "sector": "Technology"},
    {"symbol": "INTU", "name": "Intuit Inc.", "sector": "Technology"},
    {"symbol": "NOW", "name": "ServiceNow, Inc.", "sector": "Technology"},
    {"symbol": "UBER", "name": "Uber Technologies, Inc.", "sector": "Technology"},
    {"symbol": "MSI", "name": "Motorola Solutions, Inc.", "sector": "Technology"},
    {"symbol": "APH", "name": "Amphenol Corporation", "sector": "Technology"},
    {"symbol": "HPQ", "name": "HP Inc.", "sector": "Technology"},
    {"symbol": "DELL", "name": "Dell Technologies Inc.", "sector": "Technology"},

    # Financials
    {"symbol": "BRK.B", "name": "Berkshire Hathaway Inc.", "sector": "Financials"},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "sector": "Financials"},
    {"symbol": "V", "name": "Visa Inc.", "sector": "Financials"},
    {"symbol": "MA", "name": "Mastercard Incorporated", "sector": "Financials"},
    {"symbol": "BAC", "name": "Bank of America Corporation", "sector": "Financials"},
    {"symbol": "WFC", "name": "Wells Fargo & Company", "sector": "Financials"},
    {"symbol": "GS", "name": "The Goldman Sachs Group, Inc.", "sector": "Financials"},
    {"symbol": "MS", "name": "Morgan Stanley", "sector": "Financials"},
    {"symbol": "SPGI", "name": "S&P Global Inc.", "sector": "Financials"},
    {"symbol": "AXP", "name": "American Express Company", "sector": "Financials"},
    {"symbol": "C", "name": "Citigroup Inc.", "sector": "Financials"},
    {"symbol": "BLK", "name": "BlackRock, Inc.", "sector": "Financials"},
    {"symbol": "SCHW", "name": "The Charles Schwab Corporation", "sector": "Financials"},
    {"symbol": "PGR", "name": "Progressive Corporation", "sector": "Financials"},
    {"symbol": "CB", "name": "Chubb Limited", "sector": "Financials"},
    {"symbol": "PNC", "name": "The PNC Financial Services Group, Inc.", "sector": "Financials"},
    {"symbol": "USB", "name": "U.S. Bancorp", "sector": "Financials"},
    {"symbol": "TFC", "name": "Truist Financial Corporation", "sector": "Financials"},
    {"symbol": "AIG", "name": "American International Group, Inc.", "sector": "Financials"},
    {"symbol": "MET", "name": "MetLife, Inc.", "sector": "Financials"},
    {"symbol": "ICE", "name": "Intercontinental Exchange, Inc.", "sector": "Financials"},
    {"symbol": "CME", "name": "CME Group Inc.", "sector": "Financials"},
    {"symbol": "COF", "name": "Capital One Financial Corporation", "sector": "Financials"},

    # Healthcare
    {"symbol": "LLY", "name": "Eli Lilly and Company", "sector": "Healthcare"},
    {"symbol": "UNH", "name": "UnitedHealth Group Incorporated", "sector": "Healthcare"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Healthcare"},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "sector": "Healthcare"},
    {"symbol": "MRK", "name": "Merck & Co., Inc.", "sector": "Healthcare"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc.", "sector": "Healthcare"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Healthcare"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "sector": "Healthcare"},
    {"symbol": "DHR", "name": "Danaher Corporation", "sector": "Healthcare"},
    {"symbol": "ISRG", "name": "Intuitive Surgical, Inc.", "sector": "Healthcare"},
    {"symbol": "AMGN", "name": "Amgen Inc.", "sector": "Healthcare"},
    {"symbol": "BSX", "name": "Boston Scientific Corporation", "sector": "Healthcare"},
    {"symbol": "SYK", "name": "Stryker Corporation", "sector": "Healthcare"},
    {"symbol": "MDT", "name": "Medtronic plc", "sector": "Healthcare"},
    {"symbol": "GILD", "name": "Gilead Sciences, Inc.", "sector": "Healthcare"},
    {"symbol": "CI", "name": "The Cigna Group", "sector": "Healthcare"},
    {"symbol": "VRTX", "name": "Vertex Pharmaceuticals Incorporated", "sector": "Healthcare"},
    {"symbol": "REGN", "name": "Regeneron Pharmaceuticals, Inc.", "sector": "Healthcare"},
    {"symbol": "CVS", "name": "CVS Health Corporation", "sector": "Healthcare"},
    {"symbol": "ELV", "name": "Elevance Health, Inc.", "sector": "Healthcare"},
    {"symbol": "HCA", "name": "HCA Healthcare, Inc.", "sector": "Healthcare"},

    # Consumer Discretionary
    {"symbol": "AMZN", "name": "Amazon.com, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "TSLA", "name": "Tesla, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "HD", "name": "The Home Depot, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "MCD", "name": "McDonald's Corporation", "sector": "Consumer Discretionary"},
    {"symbol": "BKNG", "name": "Booking Holdings Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "TJX", "name": "The TJX Companies, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "LOW", "name": "Lowe's Companies, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "SBUX", "name": "Starbucks Corporation", "sector": "Consumer Discretionary"},
    {"symbol": "NKE", "name": "NIKE, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "CMG", "name": "Chipotle Mexican Grill, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "ORLY", "name": "O'Reilly Automotive, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "MAR", "name": "Marriott International, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "GM", "name": "General Motors Company", "sector": "Consumer Discretionary"},
    {"symbol": "F", "name": "Ford Motor Company", "sector": "Consumer Discretionary"},
    {"symbol": "ROST", "name": "Ross Stores, Inc.", "sector": "Consumer Discretionary"},

    # Consumer Staples
    {"symbol": "WMT", "name": "Walmart Inc.", "sector": "Consumer Staples"},
    {"symbol": "PG", "name": "Procter & Gamble Co.", "sector": "Consumer Staples"},
    {"symbol": "COST", "name": "Costco Wholesale Corporation", "sector": "Consumer Staples"},
    {"symbol": "KO", "name": "The Coca-Cola Company", "sector": "Consumer Staples"},
    {"symbol": "PEP", "name": "PepsiCo, Inc.", "sector": "Consumer Staples"},
    {"symbol": "PM", "name": "Philip Morris International Inc.", "sector": "Consumer Staples"},
    {"symbol": "MO", "name": "Altria Group, Inc.", "sector": "Consumer Staples"},
    {"symbol": "MDLZ", "name": "Mondelez International, Inc.", "sector": "Consumer Staples"},
    {"symbol": "CL", "name": "Colgate-Palmolive Company", "sector": "Consumer Staples"},
    {"symbol": "TGT", "name": "Target Corporation", "sector": "Consumer Staples"},
    {"symbol": "KMB", "name": "Kimberly-Clark Corporation", "sector": "Consumer Staples"},
    {"symbol": "GIS", "name": "General Mills, Inc.", "sector": "Consumer Staples"},
    {"symbol": "SYY", "name": "Sysco Corporation", "sector": "Consumer Staples"},
    {"symbol": "KR", "name": "The Kroger Co.", "sector": "Consumer Staples"},

    # Energy
    {"symbol": "XOM", "name": "Exxon Mobil Corporation", "sector": "Energy"},
    {"symbol": "CVX", "name": "Chevron Corporation", "sector": "Energy"},
    {"symbol": "COP", "name": "ConocoPhillips", "sector": "Energy"},
    {"symbol": "SLB", "name": "Schlumberger Limited", "sector": "Energy"},
    {"symbol": "EOG", "name": "EOG Resources, Inc.", "sector": "Energy"},
    {"symbol": "MPC", "name": "Marathon Petroleum Corporation", "sector": "Energy"},
    {"symbol": "PSX", "name": "Phillips 66", "sector": "Energy"},
    {"symbol": "WMB", "name": "Williams Companies, Inc.", "sector": "Energy"},
    {"symbol": "OXY", "name": "Occidental Petroleum Corporation", "sector": "Energy"},
    {"symbol": "VLO", "name": "Valero Energy Corporation", "sector": "Energy"},
    {"symbol": "KMI", "name": "Kinder Morgan, Inc.", "sector": "Energy"},

    # Industrials
    {"symbol": "GE", "name": "GE Aerospace", "sector": "Industrials"},
    {"symbol": "CAT", "name": "Caterpillar Inc.", "sector": "Industrials"},
    {"symbol": "RTX", "name": "RTX Corporation", "sector": "Industrials"},
    {"symbol": "UNP", "name": "Union Pacific Corporation", "sector": "Industrials"},
    {"symbol": "HON", "name": "Honeywell International Inc.", "sector": "Industrials"},
    {"symbol": "BA", "name": "The Boeing Company", "sector": "Industrials"},
    {"symbol": "DE", "name": "Deere & Company", "sector": "Industrials"},
    {"symbol": "UPS", "name": "United Parcel Service, Inc.", "sector": "Industrials"},
    {"symbol": "LMT", "name": "Lockheed Martin Corporation", "sector": "Industrials"},
    {"symbol": "ADP", "name": "Automatic Data Processing, Inc.", "sector": "Industrials"},
    {"symbol": "GD", "name": "General Dynamics Corporation", "sector": "Industrials"},
    {"symbol": "NOC", "name": "Northrop Grumman Corporation", "sector": "Industrials"},
    {"symbol": "ETN", "name": "Eaton Corporation plc", "sector": "Industrials"},
    {"symbol": "ITW", "name": "Illinois Tool Works Inc.", "sector": "Industrials"},
    {"symbol": "CSX", "name": "CSX Corporation", "sector": "Industrials"},
    {"symbol": "NSC", "name": "Norfolk Southern Corporation", "sector": "Industrials"},
    {"symbol": "FDX", "name": "FedEx Corporation", "sector": "Industrials"},
    {"symbol": "WM", "name": "Waste Management, Inc.", "sector": "Industrials"},
    {"symbol": "EMR", "name": "Emerson Electric Co.", "sector": "Industrials"},

    # Utilities
    {"symbol": "NEE", "name": "NextEra Energy, Inc.", "sector": "Utilities"},
    {"symbol": "SO", "name": "The Southern Company", "sector": "Utilities"},
    {"symbol": "DUK", "name": "Duke Energy Corporation", "sector": "Utilities"},
    {"symbol": "AEP", "name": "American Electric Power Company, Inc.", "sector": "Utilities"},
    {"symbol": "SRE", "name": "Sempra", "sector": "Utilities"},
    {"symbol": "D", "name": "Dominion Energy, Inc.", "sector": "Utilities"},
    {"symbol": "EXC", "name": "Exelon Corporation", "sector": "Utilities"},
    {"symbol": "XEL", "name": "Xcel Energy Inc.", "sector": "Utilities"},
    {"symbol": "ED", "name": "Consolidated Edison, Inc.", "sector": "Utilities"},
    {"symbol": "PEG", "name": "Public Service Enterprise Group Incorporated", "sector": "Utilities"},

    # Materials
    {"symbol": "LIN", "name": "Linde plc", "sector": "Materials"},
    {"symbol": "SHW", "name": "The Sherwin-Williams Company", "sector": "Materials"},
    {"symbol": "APD", "name": "Air Products and Chemicals, Inc.", "sector": "Materials"},
    {"symbol": "ECL", "name": "Ecolab Inc.", "sector": "Materials"},
    {"symbol": "FCX", "name": "Freeport-McMoRan Inc.", "sector": "Materials"},
    {"symbol": "NEM", "name": "Newmont Corporation", "sector": "Materials"},
    {"symbol": "NUE", "name": "Nucor Corporation", "sector": "Materials"},
    {"symbol": "DOW", "name": "Dow Inc.", "sector": "Materials"},

    # Real Estate
    {"symbol": "PLD", "name": "Prologis, Inc.", "sector": "Real Estate"},
    {"symbol": "AMT", "name": "American Tower Corporation", "sector": "Real Estate"},
    {"symbol": "EQIX", "name": "Equinix, Inc.", "sector": "Real Estate"},
    {"symbol": "WELL", "name": "Welltower Inc.", "sector": "Real Estate"},
    {"symbol": "DLR", "name": "Digital Realty Trust, Inc.", "sector": "Real Estate"},
    {"symbol": "SPG", "name": "Simon Property Group, Inc.", "sector": "Real Estate"},
    {"symbol": "O", "name": "Realty Income Corporation", "sector": "Real Estate"},
    {"symbol": "PSA", "name": "Public Storage", "sector": "Real Estate"},

    # Communication Services
    {"symbol": "GOOGL", "name": "Alphabet Inc.", "sector": "Communication Services"},
    {"symbol": "META", "name": "Meta Platforms, Inc.", "sector": "Communication Services"},
    {"symbol": "NFLX", "name": "Netflix, Inc.", "sector": "Communication Services"},
    {"symbol": "DIS", "name": "The Walt Disney Company", "sector": "Communication Services"},
    {"symbol": "CMCSA", "name": "Comcast Corporation", "sector": "Communication Services"},
    {"symbol": "TMUS", "name": "T-Mobile US, Inc.", "sector": "Communication Services"},
    {"symbol": "VZ", "name": "Verizon Communications Inc.", "sector": "Communication Services"},
    {"symbol": "T", "name": "AT&T Inc.", "sector": "Communication Services"},
    {"symbol": "EA", "name": "Electronic Arts Inc.", "sector": "Communication Services"},
    {"symbol": "WBD", "name": "Warner Bros. Discovery, Inc.", "sector": "Communication Services"},
]
