"""
Static S&P 500 constituent list (ticker, company name, GICS sector).

Why static instead of fetched: FMP deprecated their `/sp500-constituent` endpoint for
anyone without a legacy subscription predating August 2025 — it now 403s on a standard
API key (confirmed directly against the live API while building this). Index membership
changes only a handful of times a year, so a periodically-refreshed static list is a
reasonable trade for not needing a paid FMP tier just to enumerate the universe.

This is a curated subset (~467 of the largest, most liquid S&P 500 constituents spanning
all 11 GICS sectors) rather than a claimed-complete 503-ticker list — accuracy of a full
list typed from memory can't be guaranteed, and a partial-but-correct universe is more
useful than a complete-but-wrong one for a screener. To expand toward full coverage,
either upgrade the FMP plan and swap this out for a live constituent call, or extend this
list by hand from a public source (e.g. Wikipedia's "List of S&P 500 companies").

Expanded from ~168 to ~467 on 2026-09-06 after a user search (CTSH) landed on a name that
wasn't covered yet — still not a claimed-complete list, just a bigger one. A ticker search
that still comes back "not covered" (see frontend/src/app/stock/[ticker]/page.tsx) means
extend this list further, not that something is broken.
"""

SP500_UNIVERSE: list[dict[str, str]] = [
    # Technology
    {"symbol": "AAPL", "name": "Apple Inc.", "sector": "Technology"},
    {"symbol": "MSFT", "name": "Microsoft Corporation", "sector": "Technology"},
    {"symbol": "NVDA", "name": "NVIDIA Corporation", "sector": "Technology"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "sector": "Technology"},
    {"symbol": "ORCL", "name": "Oracle Corporation", "sector": "Technology"},
    {"symbol": "CRM", "name": "Salesforce, Inc.", "sector": "Technology"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "sector": "Technology"},
    {"symbol": "AMD", "name": "Advanced Micro Devices, Inc.", "sector": "Technology"},
    {"symbol": "CSCO", "name": "Cisco Systems, Inc.", "sector": "Technology"},
    {"symbol": "ACN", "name": "Accenture plc", "sector": "Technology"},
    {"symbol": "IBM", "name": "International Business Machines Corporation", "sector": "Technology"},
    {"symbol": "INTC", "name": "Intel Corporation", "sector": "Technology"},
    {"symbol": "TXN", "name": "Texas Instruments Incorporated", "sector": "Technology"},
    {"symbol": "QCOM", "name": "QUALCOMM Incorporated", "sector": "Technology"},
    {"symbol": "AMAT", "name": "Applied Materials, Inc.", "sector": "Technology"},
    {"symbol": "MU", "name": "Micron Technology, Inc.", "sector": "Technology"},
    {"symbol": "LRCX", "name": "Lam Research Corporation", "sector": "Technology"},
    {"symbol": "ADI", "name": "Analog Devices, Inc.", "sector": "Technology"},
    {"symbol": "KLAC", "name": "KLA Corporation", "sector": "Technology"},
    {"symbol": "PANW", "name": "Palo Alto Networks, Inc.", "sector": "Technology"},
    {"symbol": "SNPS", "name": "Synopsys, Inc.", "sector": "Technology"},
    {"symbol": "CDNS", "name": "Cadence Design Systems, Inc.", "sector": "Technology"},
    {"symbol": "INTU", "name": "Intuit Inc.", "sector": "Technology"},
    {"symbol": "NOW", "name": "ServiceNow, Inc.", "sector": "Technology"},
    {"symbol": "UBER", "name": "Uber Technologies, Inc.", "sector": "Technology"},
    {"symbol": "MSI", "name": "Motorola Solutions, Inc.", "sector": "Technology"},
    {"symbol": "APH", "name": "Amphenol Corporation", "sector": "Technology"},
    {"symbol": "HPQ", "name": "HP Inc.", "sector": "Technology"},
    {"symbol": "DELL", "name": "Dell Technologies Inc.", "sector": "Technology"},
    {"symbol": "CTSH", "name": "Cognizant Technology Solutions Corporation", "sector": "Technology"},
    {"symbol": "PYPL", "name": "PayPal Holdings, Inc.", "sector": "Technology"},
    {"symbol": "ADSK", "name": "Autodesk, Inc.", "sector": "Technology"},
    {"symbol": "WDAY", "name": "Workday, Inc.", "sector": "Technology"},
    {"symbol": "FTNT", "name": "Fortinet, Inc.", "sector": "Technology"},
    {"symbol": "PAYX", "name": "Paychex, Inc.", "sector": "Technology"},
    {"symbol": "ANSS", "name": "ANSYS, Inc.", "sector": "Technology"},
    {"symbol": "CDW", "name": "CDW Corporation", "sector": "Technology"},
    {"symbol": "FICO", "name": "Fair Isaac Corporation", "sector": "Technology"},
    {"symbol": "GEN", "name": "Gen Digital Inc.", "sector": "Technology"},
    {"symbol": "GLW", "name": "Corning Incorporated", "sector": "Technology"},
    {"symbol": "HPE", "name": "Hewlett Packard Enterprise Company", "sector": "Technology"},
    {"symbol": "IT", "name": "Gartner, Inc.", "sector": "Technology"},
    {"symbol": "JBL", "name": "Jabil Inc.", "sector": "Technology"},
    {"symbol": "JNPR", "name": "Juniper Networks, Inc.", "sector": "Technology"},
    {"symbol": "KEYS", "name": "Keysight Technologies, Inc.", "sector": "Technology"},
    {"symbol": "MCHP", "name": "Microchip Technology Incorporated", "sector": "Technology"},
    {"symbol": "MPWR", "name": "Monolithic Power Systems, Inc.", "sector": "Technology"},
    {"symbol": "NTAP", "name": "NetApp, Inc.", "sector": "Technology"},
    {"symbol": "NXPI", "name": "NXP Semiconductors N.V.", "sector": "Technology"},
    {"symbol": "ON", "name": "ON Semiconductor Corporation", "sector": "Technology"},
    {"symbol": "PTC", "name": "PTC Inc.", "sector": "Technology"},
    {"symbol": "ROP", "name": "Roper Technologies, Inc.", "sector": "Technology"},
    {"symbol": "STX", "name": "Seagate Technology Holdings plc", "sector": "Technology"},
    {"symbol": "SWKS", "name": "Skyworks Solutions, Inc.", "sector": "Technology"},
    {"symbol": "TDY", "name": "Teledyne Technologies Incorporated", "sector": "Technology"},
    {"symbol": "TER", "name": "Teradyne, Inc.", "sector": "Technology"},
    {"symbol": "TRMB", "name": "Trimble Inc.", "sector": "Technology"},
    {"symbol": "TYL", "name": "Tyler Technologies, Inc.", "sector": "Technology"},
    {"symbol": "WDC", "name": "Western Digital Corporation", "sector": "Technology"},
    {"symbol": "ZBRA", "name": "Zebra Technologies Corporation", "sector": "Technology"},
    {"symbol": "AKAM", "name": "Akamai Technologies, Inc.", "sector": "Technology"},
    {"symbol": "GDDY", "name": "GoDaddy Inc.", "sector": "Technology"},
    {"symbol": "VRSN", "name": "VeriSign, Inc.", "sector": "Technology"},

    # Financials
    {"symbol": "BRK.B", "name": "Berkshire Hathaway Inc.", "sector": "Financials"},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "sector": "Financials"},
    {"symbol": "V", "name": "Visa Inc.", "sector": "Financials"},
    {"symbol": "MA", "name": "Mastercard Incorporated", "sector": "Financials"},
    {"symbol": "BAC", "name": "Bank of America Corporation", "sector": "Financials"},
    {"symbol": "WFC", "name": "Wells Fargo & Company", "sector": "Financials"},
    {"symbol": "GS", "name": "The Goldman Sachs Group, Inc.", "sector": "Financials"},
    {"symbol": "MS", "name": "Morgan Stanley", "sector": "Financials"},
    {"symbol": "SPGI", "name": "S&P Global Inc.", "sector": "Financials"},
    {"symbol": "AXP", "name": "American Express Company", "sector": "Financials"},
    {"symbol": "C", "name": "Citigroup Inc.", "sector": "Financials"},
    {"symbol": "BLK", "name": "BlackRock, Inc.", "sector": "Financials"},
    {"symbol": "SCHW", "name": "The Charles Schwab Corporation", "sector": "Financials"},
    {"symbol": "PGR", "name": "Progressive Corporation", "sector": "Financials"},
    {"symbol": "CB", "name": "Chubb Limited", "sector": "Financials"},
    {"symbol": "PNC", "name": "The PNC Financial Services Group, Inc.", "sector": "Financials"},
    {"symbol": "USB", "name": "U.S. Bancorp", "sector": "Financials"},
    {"symbol": "TFC", "name": "Truist Financial Corporation", "sector": "Financials"},
    {"symbol": "AIG", "name": "American International Group, Inc.", "sector": "Financials"},
    {"symbol": "MET", "name": "MetLife, Inc.", "sector": "Financials"},
    {"symbol": "ICE", "name": "Intercontinental Exchange, Inc.", "sector": "Financials"},
    {"symbol": "CME", "name": "CME Group Inc.", "sector": "Financials"},
    {"symbol": "COF", "name": "Capital One Financial Corporation", "sector": "Financials"},
    {"symbol": "MSCI", "name": "MSCI Inc.", "sector": "Financials"},
    {"symbol": "TRV", "name": "The Travelers Companies, Inc.", "sector": "Financials"},
    {"symbol": "ALL", "name": "The Allstate Corporation", "sector": "Financials"},
    {"symbol": "AFL", "name": "Aflac Incorporated", "sector": "Financials"},
    {"symbol": "AJG", "name": "Arthur J. Gallagher & Co.", "sector": "Financials"},
    {"symbol": "AMP", "name": "Ameriprise Financial, Inc.", "sector": "Financials"},
    {"symbol": "AON", "name": "Aon plc", "sector": "Financials"},
    {"symbol": "BEN", "name": "Franklin Resources, Inc.", "sector": "Financials"},
    {"symbol": "BK", "name": "The Bank of New York Mellon Corporation", "sector": "Financials"},
    {"symbol": "BRO", "name": "Brown & Brown, Inc.", "sector": "Financials"},
    {"symbol": "CBOE", "name": "Cboe Global Markets, Inc.", "sector": "Financials"},
    {"symbol": "CINF", "name": "Cincinnati Financial Corporation", "sector": "Financials"},
    {"symbol": "DFS", "name": "Discover Financial Services", "sector": "Financials"},
    {"symbol": "EG", "name": "Everest Group, Ltd.", "sector": "Financials"},
    {"symbol": "FDS", "name": "FactSet Research Systems Inc.", "sector": "Financials"},
    {"symbol": "FI", "name": "Fiserv, Inc.", "sector": "Financials"},
    {"symbol": "FIS", "name": "Fidelity National Information Services, Inc.", "sector": "Financials"},
    {"symbol": "FITB", "name": "Fifth Third Bancorp", "sector": "Financials"},
    {"symbol": "GL", "name": "Globe Life Inc.", "sector": "Financials"},
    {"symbol": "GPN", "name": "Global Payments Inc.", "sector": "Financials"},
    {"symbol": "HBAN", "name": "Huntington Bancshares Incorporated", "sector": "Financials"},
    {"symbol": "HIG", "name": "The Hartford Financial Services Group, Inc.", "sector": "Financials"},
    {"symbol": "IVZ", "name": "Invesco Ltd.", "sector": "Financials"},
    {"symbol": "JKHY", "name": "Jack Henry & Associates, Inc.", "sector": "Financials"},
    {"symbol": "KEY", "name": "KeyCorp", "sector": "Financials"},
    {"symbol": "L", "name": "Loews Corporation", "sector": "Financials"},
    {"symbol": "MCO", "name": "Moody's Corporation", "sector": "Financials"},
    {"symbol": "MKTX", "name": "MarketAxess Holdings Inc.", "sector": "Financials"},
    {"symbol": "MMC", "name": "Marsh & McLennan Companies, Inc.", "sector": "Financials"},
    {"symbol": "MTB", "name": "M&T Bank Corporation", "sector": "Financials"},
    {"symbol": "NDAQ", "name": "Nasdaq, Inc.", "sector": "Financials"},
    {"symbol": "NTRS", "name": "Northern Trust Corporation", "sector": "Financials"},
    {"symbol": "PFG", "name": "Principal Financial Group, Inc.", "sector": "Financials"},
    {"symbol": "PRU", "name": "Prudential Financial, Inc.", "sector": "Financials"},
    {"symbol": "RF", "name": "Regions Financial Corporation", "sector": "Financials"},
    {"symbol": "RJF", "name": "Raymond James Financial, Inc.", "sector": "Financials"},
    {"symbol": "STT", "name": "State Street Corporation", "sector": "Financials"},
    {"symbol": "SYF", "name": "Synchrony Financial", "sector": "Financials"},
    {"symbol": "WTW", "name": "Willis Towers Watson Public Limited Company", "sector": "Financials"},
    {"symbol": "ZION", "name": "Zions Bancorporation", "sector": "Financials"},
    {"symbol": "ACGL", "name": "Arch Capital Group Ltd.", "sector": "Financials"},
    {"symbol": "AIZ", "name": "Assurant, Inc.", "sector": "Financials"},
    {"symbol": "WRB", "name": "W. R. Berkley Corporation", "sector": "Financials"},

    # Healthcare
    {"symbol": "LLY", "name": "Eli Lilly and Company", "sector": "Healthcare"},
    {"symbol": "UNH", "name": "UnitedHealth Group Incorporated", "sector": "Healthcare"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Healthcare"},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "sector": "Healthcare"},
    {"symbol": "MRK", "name": "Merck & Co., Inc.", "sector": "Healthcare"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc.", "sector": "Healthcare"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Healthcare"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "sector": "Healthcare"},
    {"symbol": "DHR", "name": "Danaher Corporation", "sector": "Healthcare"},
    {"symbol": "ISRG", "name": "Intuitive Surgical, Inc.", "sector": "Healthcare"},
    {"symbol": "AMGN", "name": "Amgen Inc.", "sector": "Healthcare"},
    {"symbol": "BSX", "name": "Boston Scientific Corporation", "sector": "Healthcare"},
    {"symbol": "SYK", "name": "Stryker Corporation", "sector": "Healthcare"},
    {"symbol": "MDT", "name": "Medtronic plc", "sector": "Healthcare"},
    {"symbol": "GILD", "name": "Gilead Sciences, Inc.", "sector": "Healthcare"},
    {"symbol": "CI", "name": "The Cigna Group", "sector": "Healthcare"},
    {"symbol": "VRTX", "name": "Vertex Pharmaceuticals Incorporated", "sector": "Healthcare"},
    {"symbol": "REGN", "name": "Regeneron Pharmaceuticals, Inc.", "sector": "Healthcare"},
    {"symbol": "CVS", "name": "CVS Health Corporation", "sector": "Healthcare"},
    {"symbol": "ELV", "name": "Elevance Health, Inc.", "sector": "Healthcare"},
    {"symbol": "HCA", "name": "HCA Healthcare, Inc.", "sector": "Healthcare"},
    {"symbol": "A", "name": "Agilent Technologies, Inc.", "sector": "Healthcare"},
    {"symbol": "ALGN", "name": "Align Technology, Inc.", "sector": "Healthcare"},
    {"symbol": "BAX", "name": "Baxter International Inc.", "sector": "Healthcare"},
    {"symbol": "BDX", "name": "Becton, Dickinson and Company", "sector": "Healthcare"},
    {"symbol": "BIIB", "name": "Biogen Inc.", "sector": "Healthcare"},
    {"symbol": "BIO", "name": "Bio-Rad Laboratories, Inc.", "sector": "Healthcare"},
    {"symbol": "CAH", "name": "Cardinal Health, Inc.", "sector": "Healthcare"},
    {"symbol": "CNC", "name": "Centene Corporation", "sector": "Healthcare"},
    {"symbol": "COO", "name": "The Cooper Companies, Inc.", "sector": "Healthcare"},
    {"symbol": "COR", "name": "Cencora, Inc.", "sector": "Healthcare"},
    {"symbol": "CRL", "name": "Charles River Laboratories International, Inc.", "sector": "Healthcare"},
    {"symbol": "DGX", "name": "Quest Diagnostics Incorporated", "sector": "Healthcare"},
    {"symbol": "DVA", "name": "DaVita Inc.", "sector": "Healthcare"},
    {"symbol": "DXCM", "name": "DexCom, Inc.", "sector": "Healthcare"},
    {"symbol": "EW", "name": "Edwards Lifesciences Corporation", "sector": "Healthcare"},
    {"symbol": "GEHC", "name": "GE HealthCare Technologies Inc.", "sector": "Healthcare"},
    {"symbol": "HOLX", "name": "Hologic, Inc.", "sector": "Healthcare"},
    {"symbol": "HSIC", "name": "Henry Schein, Inc.", "sector": "Healthcare"},
    {"symbol": "HUM", "name": "Humana Inc.", "sector": "Healthcare"},
    {"symbol": "IDXX", "name": "IDEXX Laboratories, Inc.", "sector": "Healthcare"},
    {"symbol": "ILMN", "name": "Illumina, Inc.", "sector": "Healthcare"},
    {"symbol": "INCY", "name": "Incyte Corporation", "sector": "Healthcare"},
    {"symbol": "IQV", "name": "IQVIA Holdings Inc.", "sector": "Healthcare"},
    {"symbol": "LH", "name": "Labcorp Holdings Inc.", "sector": "Healthcare"},
    {"symbol": "MCK", "name": "McKesson Corporation", "sector": "Healthcare"},
    {"symbol": "MOH", "name": "Molina Healthcare, Inc.", "sector": "Healthcare"},
    {"symbol": "MRNA", "name": "Moderna, Inc.", "sector": "Healthcare"},
    {"symbol": "MTD", "name": "Mettler-Toledo International Inc.", "sector": "Healthcare"},
    {"symbol": "PODD", "name": "Insulet Corporation", "sector": "Healthcare"},
    {"symbol": "RMD", "name": "ResMed Inc.", "sector": "Healthcare"},
    {"symbol": "RVTY", "name": "Revvity, Inc.", "sector": "Healthcare"},
    {"symbol": "TECH", "name": "Bio-Techne Corporation", "sector": "Healthcare"},
    {"symbol": "TFX", "name": "Teleflex Incorporated", "sector": "Healthcare"},
    {"symbol": "UHS", "name": "Universal Health Services, Inc.", "sector": "Healthcare"},
    {"symbol": "VTRS", "name": "Viatris Inc.", "sector": "Healthcare"},
    {"symbol": "WAT", "name": "Waters Corporation", "sector": "Healthcare"},
    {"symbol": "WST", "name": "West Pharmaceutical Services, Inc.", "sector": "Healthcare"},
    {"symbol": "ZBH", "name": "Zimmer Biomet Holdings, Inc.", "sector": "Healthcare"},
    {"symbol": "ZTS", "name": "Zoetis Inc.", "sector": "Healthcare"},

    # Consumer Discretionary
    {"symbol": "AMZN", "name": "Amazon.com, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "TSLA", "name": "Tesla, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "HD", "name": "The Home Depot, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "MCD", "name": "McDonald's Corporation", "sector": "Consumer Discretionary"},
    {"symbol": "BKNG", "name": "Booking Holdings Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "TJX", "name": "The TJX Companies, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "LOW", "name": "Lowe's Companies, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "SBUX", "name": "Starbucks Corporation", "sector": "Consumer Discretionary"},
    {"symbol": "NKE", "name": "NIKE, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "CMG", "name": "Chipotle Mexican Grill, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "ORLY", "name": "O'Reilly Automotive, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "MAR", "name": "Marriott International, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "GM", "name": "General Motors Company", "sector": "Consumer Discretionary"},
    {"symbol": "F", "name": "Ford Motor Company", "sector": "Consumer Discretionary"},
    {"symbol": "ROST", "name": "Ross Stores, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "ABNB", "name": "Airbnb, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "AZO", "name": "AutoZone, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "BBY", "name": "Best Buy Co., Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "BWA", "name": "BorgWarner Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "CCL", "name": "Carnival Corporation & plc", "sector": "Consumer Discretionary"},
    {"symbol": "CZR", "name": "Caesars Entertainment, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "DECK", "name": "Deckers Outdoor Corporation", "sector": "Consumer Discretionary"},
    {"symbol": "DHI", "name": "D.R. Horton, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "DPZ", "name": "Domino's Pizza, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "EBAY", "name": "eBay Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "ETSY", "name": "Etsy, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "EXPE", "name": "Expedia Group, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "GPC", "name": "Genuine Parts Company", "sector": "Consumer Discretionary"},
    {"symbol": "GRMN", "name": "Garmin Ltd.", "sector": "Consumer Discretionary"},
    {"symbol": "HAS", "name": "Hasbro, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "HLT", "name": "Hilton Worldwide Holdings Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "KMX", "name": "CarMax, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "LEN", "name": "Lennar Corporation", "sector": "Consumer Discretionary"},
    {"symbol": "LKQ", "name": "LKQ Corporation", "sector": "Consumer Discretionary"},
    {"symbol": "LVS", "name": "Las Vegas Sands Corp.", "sector": "Consumer Discretionary"},
    {"symbol": "LULU", "name": "Lululemon Athletica Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "MGM", "name": "MGM Resorts International", "sector": "Consumer Discretionary"},
    {"symbol": "MHK", "name": "Mohawk Industries, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "NCLH", "name": "Norwegian Cruise Line Holdings Ltd.", "sector": "Consumer Discretionary"},
    {"symbol": "NVR", "name": "NVR, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "PHM", "name": "PulteGroup, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "POOL", "name": "Pool Corporation", "sector": "Consumer Discretionary"},
    {"symbol": "RCL", "name": "Royal Caribbean Cruises Ltd.", "sector": "Consumer Discretionary"},
    {"symbol": "RL", "name": "Ralph Lauren Corporation", "sector": "Consumer Discretionary"},
    {"symbol": "TPR", "name": "Tapestry, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "TSCO", "name": "Tractor Supply Company", "sector": "Consumer Discretionary"},
    {"symbol": "ULTA", "name": "Ulta Beauty, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "WYNN", "name": "Wynn Resorts, Limited", "sector": "Consumer Discretionary"},
    {"symbol": "YUM", "name": "Yum! Brands, Inc.", "sector": "Consumer Discretionary"},
    {"symbol": "APTV", "name": "Aptiv PLC", "sector": "Consumer Discretionary"},

    # Consumer Staples
    {"symbol": "WMT", "name": "Walmart Inc.", "sector": "Consumer Staples"},
    {"symbol": "PG", "name": "Procter & Gamble Co.", "sector": "Consumer Staples"},
    {"symbol": "COST", "name": "Costco Wholesale Corporation", "sector": "Consumer Staples"},
    {"symbol": "KO", "name": "The Coca-Cola Company", "sector": "Consumer Staples"},
    {"symbol": "PEP", "name": "PepsiCo, Inc.", "sector": "Consumer Staples"},
    {"symbol": "PM", "name": "Philip Morris International Inc.", "sector": "Consumer Staples"},
    {"symbol": "MO", "name": "Altria Group, Inc.", "sector": "Consumer Staples"},
    {"symbol": "MDLZ", "name": "Mondelez International, Inc.", "sector": "Consumer Staples"},
    {"symbol": "CL", "name": "Colgate-Palmolive Company", "sector": "Consumer Staples"},
    {"symbol": "TGT", "name": "Target Corporation", "sector": "Consumer Staples"},
    {"symbol": "KMB", "name": "Kimberly-Clark Corporation", "sector": "Consumer Staples"},
    {"symbol": "GIS", "name": "General Mills, Inc.", "sector": "Consumer Staples"},
    {"symbol": "SYY", "name": "Sysco Corporation", "sector": "Consumer Staples"},
    {"symbol": "KR", "name": "The Kroger Co.", "sector": "Consumer Staples"},
    {"symbol": "ADM", "name": "Archer-Daniels-Midland Company", "sector": "Consumer Staples"},
    {"symbol": "BF.B", "name": "Brown-Forman Corporation", "sector": "Consumer Staples"},
    {"symbol": "BG", "name": "Bunge Global SA", "sector": "Consumer Staples"},
    {"symbol": "CAG", "name": "Conagra Brands, Inc.", "sector": "Consumer Staples"},
    {"symbol": "CHD", "name": "Church & Dwight Co., Inc.", "sector": "Consumer Staples"},
    {"symbol": "CLX", "name": "The Clorox Company", "sector": "Consumer Staples"},
    {"symbol": "CPB", "name": "Campbell's Company", "sector": "Consumer Staples"},
    {"symbol": "DLTR", "name": "Dollar Tree, Inc.", "sector": "Consumer Staples"},
    {"symbol": "EL", "name": "The Estee Lauder Companies Inc.", "sector": "Consumer Staples"},
    {"symbol": "HRL", "name": "Hormel Foods Corporation", "sector": "Consumer Staples"},
    {"symbol": "HSY", "name": "The Hershey Company", "sector": "Consumer Staples"},
    {"symbol": "K", "name": "Kellanova", "sector": "Consumer Staples"},
    {"symbol": "KDP", "name": "Keurig Dr Pepper Inc.", "sector": "Consumer Staples"},
    {"symbol": "KHC", "name": "The Kraft Heinz Company", "sector": "Consumer Staples"},
    {"symbol": "KVUE", "name": "Kenvue Inc.", "sector": "Consumer Staples"},
    {"symbol": "LW", "name": "Lamb Weston Holdings, Inc.", "sector": "Consumer Staples"},
    {"symbol": "MKC", "name": "McCormick & Company, Incorporated", "sector": "Consumer Staples"},
    {"symbol": "MNST", "name": "Monster Beverage Corporation", "sector": "Consumer Staples"},
    {"symbol": "STZ", "name": "Constellation Brands, Inc.", "sector": "Consumer Staples"},
    {"symbol": "TAP", "name": "Molson Coors Beverage Company", "sector": "Consumer Staples"},
    {"symbol": "TSN", "name": "Tyson Foods, Inc.", "sector": "Consumer Staples"},
    {"symbol": "WBA", "name": "Walgreens Boots Alliance, Inc.", "sector": "Consumer Staples"},

    # Energy
    {"symbol": "XOM", "name": "Exxon Mobil Corporation", "sector": "Energy"},
    {"symbol": "CVX", "name": "Chevron Corporation", "sector": "Energy"},
    {"symbol": "COP", "name": "ConocoPhillips", "sector": "Energy"},
    {"symbol": "SLB", "name": "Schlumberger Limited", "sector": "Energy"},
    {"symbol": "EOG", "name": "EOG Resources, Inc.", "sector": "Energy"},
    {"symbol": "MPC", "name": "Marathon Petroleum Corporation", "sector": "Energy"},
    {"symbol": "PSX", "name": "Phillips 66", "sector": "Energy"},
    {"symbol": "WMB", "name": "Williams Companies, Inc.", "sector": "Energy"},
    {"symbol": "OXY", "name": "Occidental Petroleum Corporation", "sector": "Energy"},
    {"symbol": "VLO", "name": "Valero Energy Corporation", "sector": "Energy"},
    {"symbol": "KMI", "name": "Kinder Morgan, Inc.", "sector": "Energy"},
    {"symbol": "BKR", "name": "Baker Hughes Company", "sector": "Energy"},
    {"symbol": "CTRA", "name": "Coterra Energy Inc.", "sector": "Energy"},
    {"symbol": "DVN", "name": "Devon Energy Corporation", "sector": "Energy"},
    {"symbol": "FANG", "name": "Diamondback Energy, Inc.", "sector": "Energy"},
    {"symbol": "HAL", "name": "Halliburton Company", "sector": "Energy"},
    {"symbol": "HES", "name": "Hess Corporation", "sector": "Energy"},
    {"symbol": "TRGP", "name": "Targa Resources Corp.", "sector": "Energy"},
    {"symbol": "APA", "name": "APA Corporation", "sector": "Energy"},
    {"symbol": "OKE", "name": "ONEOK, Inc.", "sector": "Energy"},

    # Industrials
    {"symbol": "GE", "name": "GE Aerospace", "sector": "Industrials"},
    {"symbol": "CAT", "name": "Caterpillar Inc.", "sector": "Industrials"},
    {"symbol": "RTX", "name": "RTX Corporation", "sector": "Industrials"},
    {"symbol": "UNP", "name": "Union Pacific Corporation", "sector": "Industrials"},
    {"symbol": "HON", "name": "Honeywell International Inc.", "sector": "Industrials"},
    {"symbol": "BA", "name": "The Boeing Company", "sector": "Industrials"},
    {"symbol": "DE", "name": "Deere & Company", "sector": "Industrials"},
    {"symbol": "UPS", "name": "United Parcel Service, Inc.", "sector": "Industrials"},
    {"symbol": "LMT", "name": "Lockheed Martin Corporation", "sector": "Industrials"},
    {"symbol": "ADP", "name": "Automatic Data Processing, Inc.", "sector": "Industrials"},
    {"symbol": "GD", "name": "General Dynamics Corporation", "sector": "Industrials"},
    {"symbol": "NOC", "name": "Northrop Grumman Corporation", "sector": "Industrials"},
    {"symbol": "ETN", "name": "Eaton Corporation plc", "sector": "Industrials"},
    {"symbol": "ITW", "name": "Illinois Tool Works Inc.", "sector": "Industrials"},
    {"symbol": "CSX", "name": "CSX Corporation", "sector": "Industrials"},
    {"symbol": "NSC", "name": "Norfolk Southern Corporation", "sector": "Industrials"},
    {"symbol": "FDX", "name": "FedEx Corporation", "sector": "Industrials"},
    {"symbol": "WM", "name": "Waste Management, Inc.", "sector": "Industrials"},
    {"symbol": "EMR", "name": "Emerson Electric Co.", "sector": "Industrials"},
    {"symbol": "ALLE", "name": "Allegion plc", "sector": "Industrials"},
    {"symbol": "AME", "name": "AMETEK, Inc.", "sector": "Industrials"},
    {"symbol": "AOS", "name": "A. O. Smith Corporation", "sector": "Industrials"},
    {"symbol": "AXON", "name": "Axon Enterprise, Inc.", "sector": "Industrials"},
    {"symbol": "BR", "name": "Broadridge Financial Solutions, Inc.", "sector": "Industrials"},
    {"symbol": "CARR", "name": "Carrier Global Corporation", "sector": "Industrials"},
    {"symbol": "CHRW", "name": "C.H. Robinson Worldwide, Inc.", "sector": "Industrials"},
    {"symbol": "CMI", "name": "Cummins Inc.", "sector": "Industrials"},
    {"symbol": "CPRT", "name": "Copart, Inc.", "sector": "Industrials"},
    {"symbol": "CTAS", "name": "Cintas Corporation", "sector": "Industrials"},
    {"symbol": "DAL", "name": "Delta Air Lines, Inc.", "sector": "Industrials"},
    {"symbol": "DAY", "name": "Dayforce, Inc.", "sector": "Industrials"},
    {"symbol": "DOV", "name": "Dover Corporation", "sector": "Industrials"},
    {"symbol": "EFX", "name": "Equifax Inc.", "sector": "Industrials"},
    {"symbol": "EXPD", "name": "Expeditors International of Washington, Inc.", "sector": "Industrials"},
    {"symbol": "FAST", "name": "Fastenal Company", "sector": "Industrials"},
    {"symbol": "FTV", "name": "Fortive Corporation", "sector": "Industrials"},
    {"symbol": "GEV", "name": "GE Vernova Inc.", "sector": "Industrials"},
    {"symbol": "GNRC", "name": "Generac Holdings Inc.", "sector": "Industrials"},
    {"symbol": "GWW", "name": "W.W. Grainger, Inc.", "sector": "Industrials"},
    {"symbol": "HII", "name": "Huntington Ingalls Industries, Inc.", "sector": "Industrials"},
    {"symbol": "HUBB", "name": "Hubbell Incorporated", "sector": "Industrials"},
    {"symbol": "HWM", "name": "Howmet Aerospace Inc.", "sector": "Industrials"},
    {"symbol": "IEX", "name": "IDEX Corporation", "sector": "Industrials"},
    {"symbol": "IR", "name": "Ingersoll Rand Inc.", "sector": "Industrials"},
    {"symbol": "J", "name": "Jacobs Solutions Inc.", "sector": "Industrials"},
    {"symbol": "JBHT", "name": "J.B. Hunt Transport Services, Inc.", "sector": "Industrials"},
    {"symbol": "JCI", "name": "Johnson Controls International plc", "sector": "Industrials"},
    {"symbol": "LDOS", "name": "Leidos Holdings, Inc.", "sector": "Industrials"},
    {"symbol": "LHX", "name": "L3Harris Technologies, Inc.", "sector": "Industrials"},
    {"symbol": "LII", "name": "Lennox International Inc.", "sector": "Industrials"},
    {"symbol": "LUV", "name": "Southwest Airlines Co.", "sector": "Industrials"},
    {"symbol": "MAS", "name": "Masco Corporation", "sector": "Industrials"},
    {"symbol": "NDSN", "name": "Nordson Corporation", "sector": "Industrials"},
    {"symbol": "ODFL", "name": "Old Dominion Freight Line, Inc.", "sector": "Industrials"},
    {"symbol": "OTIS", "name": "Otis Worldwide Corporation", "sector": "Industrials"},
    {"symbol": "PAYC", "name": "Paycom Software, Inc.", "sector": "Industrials"},
    {"symbol": "PCAR", "name": "PACCAR Inc", "sector": "Industrials"},
    {"symbol": "PH", "name": "Parker-Hannifin Corporation", "sector": "Industrials"},
    {"symbol": "PNR", "name": "Pentair plc", "sector": "Industrials"},
    {"symbol": "PWR", "name": "Quanta Services, Inc.", "sector": "Industrials"},
    {"symbol": "ROK", "name": "Rockwell Automation, Inc.", "sector": "Industrials"},
    {"symbol": "ROL", "name": "Rollins, Inc.", "sector": "Industrials"},
    {"symbol": "RSG", "name": "Republic Services, Inc.", "sector": "Industrials"},
    {"symbol": "SNA", "name": "Snap-on Incorporated", "sector": "Industrials"},
    {"symbol": "SWK", "name": "Stanley Black & Decker, Inc.", "sector": "Industrials"},
    {"symbol": "TDG", "name": "TransDigm Group Incorporated", "sector": "Industrials"},
    {"symbol": "TT", "name": "Trane Technologies plc", "sector": "Industrials"},
    {"symbol": "TXT", "name": "Textron Inc.", "sector": "Industrials"},
    {"symbol": "UAL", "name": "United Airlines Holdings, Inc.", "sector": "Industrials"},
    {"symbol": "URI", "name": "United Rentals, Inc.", "sector": "Industrials"},
    {"symbol": "VLTO", "name": "Veralto Corporation", "sector": "Industrials"},
    {"symbol": "XYL", "name": "Xylem Inc.", "sector": "Industrials"},

    # Utilities
    {"symbol": "NEE", "name": "NextEra Energy, Inc.", "sector": "Utilities"},
    {"symbol": "SO", "name": "The Southern Company", "sector": "Utilities"},
    {"symbol": "DUK", "name": "Duke Energy Corporation", "sector": "Utilities"},
    {"symbol": "AEP", "name": "American Electric Power Company, Inc.", "sector": "Utilities"},
    {"symbol": "SRE", "name": "Sempra", "sector": "Utilities"},
    {"symbol": "D", "name": "Dominion Energy, Inc.", "sector": "Utilities"},
    {"symbol": "EXC", "name": "Exelon Corporation", "sector": "Utilities"},
    {"symbol": "XEL", "name": "Xcel Energy Inc.", "sector": "Utilities"},
    {"symbol": "ED", "name": "Consolidated Edison, Inc.", "sector": "Utilities"},
    {"symbol": "PEG", "name": "Public Service Enterprise Group Incorporated", "sector": "Utilities"},
    {"symbol": "AEE", "name": "Ameren Corporation", "sector": "Utilities"},
    {"symbol": "AES", "name": "The AES Corporation", "sector": "Utilities"},
    {"symbol": "ATO", "name": "Atmos Energy Corporation", "sector": "Utilities"},
    {"symbol": "AWK", "name": "American Water Works Company, Inc.", "sector": "Utilities"},
    {"symbol": "CMS", "name": "CMS Energy Corporation", "sector": "Utilities"},
    {"symbol": "CNP", "name": "CenterPoint Energy, Inc.", "sector": "Utilities"},
    {"symbol": "ES", "name": "Eversource Energy", "sector": "Utilities"},
    {"symbol": "ETR", "name": "Entergy Corporation", "sector": "Utilities"},
    {"symbol": "EVRG", "name": "Evergy, Inc.", "sector": "Utilities"},
    {"symbol": "FE", "name": "FirstEnergy Corp.", "sector": "Utilities"},
    {"symbol": "LNT", "name": "Alliant Energy Corporation", "sector": "Utilities"},
    {"symbol": "NI", "name": "NiSource Inc.", "sector": "Utilities"},
    {"symbol": "NRG", "name": "NRG Energy, Inc.", "sector": "Utilities"},
    {"symbol": "PCG", "name": "PG&E Corporation", "sector": "Utilities"},
    {"symbol": "PNW", "name": "Pinnacle West Capital Corporation", "sector": "Utilities"},
    {"symbol": "PPL", "name": "PPL Corporation", "sector": "Utilities"},
    {"symbol": "WEC", "name": "WEC Energy Group, Inc.", "sector": "Utilities"},

    # Materials
    {"symbol": "LIN", "name": "Linde plc", "sector": "Materials"},
    {"symbol": "SHW", "name": "The Sherwin-Williams Company", "sector": "Materials"},
    {"symbol": "APD", "name": "Air Products and Chemicals, Inc.", "sector": "Materials"},
    {"symbol": "ECL", "name": "Ecolab Inc.", "sector": "Materials"},
    {"symbol": "FCX", "name": "Freeport-McMoRan Inc.", "sector": "Materials"},
    {"symbol": "NEM", "name": "Newmont Corporation", "sector": "Materials"},
    {"symbol": "NUE", "name": "Nucor Corporation", "sector": "Materials"},
    {"symbol": "DOW", "name": "Dow Inc.", "sector": "Materials"},
    {"symbol": "ALB", "name": "Albemarle Corporation", "sector": "Materials"},
    {"symbol": "AMCR", "name": "Amcor plc", "sector": "Materials"},
    {"symbol": "AVY", "name": "Avery Dennison Corporation", "sector": "Materials"},
    {"symbol": "BALL", "name": "Ball Corporation", "sector": "Materials"},
    {"symbol": "CE", "name": "Celanese Corporation", "sector": "Materials"},
    {"symbol": "CF", "name": "CF Industries Holdings, Inc.", "sector": "Materials"},
    {"symbol": "CTVA", "name": "Corteva, Inc.", "sector": "Materials"},
    {"symbol": "EMN", "name": "Eastman Chemical Company", "sector": "Materials"},
    {"symbol": "FMC", "name": "FMC Corporation", "sector": "Materials"},
    {"symbol": "IFF", "name": "International Flavors & Fragrances Inc.", "sector": "Materials"},
    {"symbol": "IP", "name": "International Paper Company", "sector": "Materials"},
    {"symbol": "LYB", "name": "LyondellBasell Industries N.V.", "sector": "Materials"},
    {"symbol": "MLM", "name": "Martin Marietta Materials, Inc.", "sector": "Materials"},
    {"symbol": "MOS", "name": "The Mosaic Company", "sector": "Materials"},
    {"symbol": "PKG", "name": "Packaging Corporation of America", "sector": "Materials"},
    {"symbol": "PPG", "name": "PPG Industries, Inc.", "sector": "Materials"},
    {"symbol": "VMC", "name": "Vulcan Materials Company", "sector": "Materials"},

    # Real Estate
    {"symbol": "PLD", "name": "Prologis, Inc.", "sector": "Real Estate"},
    {"symbol": "AMT", "name": "American Tower Corporation", "sector": "Real Estate"},
    {"symbol": "EQIX", "name": "Equinix, Inc.", "sector": "Real Estate"},
    {"symbol": "WELL", "name": "Welltower Inc.", "sector": "Real Estate"},
    {"symbol": "DLR", "name": "Digital Realty Trust, Inc.", "sector": "Real Estate"},
    {"symbol": "SPG", "name": "Simon Property Group, Inc.", "sector": "Real Estate"},
    {"symbol": "O", "name": "Realty Income Corporation", "sector": "Real Estate"},
    {"symbol": "PSA", "name": "Public Storage", "sector": "Real Estate"},
    {"symbol": "ARE", "name": "Alexandria Real Estate Equities, Inc.", "sector": "Real Estate"},
    {"symbol": "AVB", "name": "AvalonBay Communities, Inc.", "sector": "Real Estate"},
    {"symbol": "BXP", "name": "BXP, Inc.", "sector": "Real Estate"},
    {"symbol": "CBRE", "name": "CBRE Group, Inc.", "sector": "Real Estate"},
    {"symbol": "CPT", "name": "Camden Property Trust", "sector": "Real Estate"},
    {"symbol": "CSGP", "name": "CoStar Group, Inc.", "sector": "Real Estate"},
    {"symbol": "DOC", "name": "Healthpeak Properties, Inc.", "sector": "Real Estate"},
    {"symbol": "EQR", "name": "Equity Residential", "sector": "Real Estate"},
    {"symbol": "ESS", "name": "Essex Property Trust, Inc.", "sector": "Real Estate"},
    {"symbol": "EXR", "name": "Extra Space Storage Inc.", "sector": "Real Estate"},
    {"symbol": "FRT", "name": "Federal Realty Investment Trust", "sector": "Real Estate"},
    {"symbol": "HST", "name": "Host Hotels & Resorts, Inc.", "sector": "Real Estate"},
    {"symbol": "INVH", "name": "Invitation Homes Inc.", "sector": "Real Estate"},
    {"symbol": "IRM", "name": "Iron Mountain Incorporated", "sector": "Real Estate"},
    {"symbol": "KIM", "name": "Kimco Realty Corporation", "sector": "Real Estate"},
    {"symbol": "MAA", "name": "Mid-America Apartment Communities, Inc.", "sector": "Real Estate"},
    {"symbol": "REG", "name": "Regency Centers Corporation", "sector": "Real Estate"},
    {"symbol": "SBAC", "name": "SBA Communications Corporation", "sector": "Real Estate"},
    {"symbol": "UDR", "name": "UDR, Inc.", "sector": "Real Estate"},
    {"symbol": "VICI", "name": "VICI Properties Inc.", "sector": "Real Estate"},
    {"symbol": "VTR", "name": "Ventas, Inc.", "sector": "Real Estate"},

    # Communication Services
    {"symbol": "GOOGL", "name": "Alphabet Inc.", "sector": "Communication Services"},
    {"symbol": "META", "name": "Meta Platforms, Inc.", "sector": "Communication Services"},
    {"symbol": "NFLX", "name": "Netflix, Inc.", "sector": "Communication Services"},
    {"symbol": "DIS", "name": "The Walt Disney Company", "sector": "Communication Services"},
    {"symbol": "CMCSA", "name": "Comcast Corporation", "sector": "Communication Services"},
    {"symbol": "TMUS", "name": "T-Mobile US, Inc.", "sector": "Communication Services"},
    {"symbol": "VZ", "name": "Verizon Communications Inc.", "sector": "Communication Services"},
    {"symbol": "T", "name": "AT&T Inc.", "sector": "Communication Services"},
    {"symbol": "EA", "name": "Electronic Arts Inc.", "sector": "Communication Services"},
    {"symbol": "WBD", "name": "Warner Bros. Discovery, Inc.", "sector": "Communication Services"},
    {"symbol": "CHTR", "name": "Charter Communications, Inc.", "sector": "Communication Services"},
    {"symbol": "FOXA", "name": "Fox Corporation", "sector": "Communication Services"},
    {"symbol": "IPG", "name": "The Interpublic Group of Companies, Inc.", "sector": "Communication Services"},
    {"symbol": "LYV", "name": "Live Nation Entertainment, Inc.", "sector": "Communication Services"},
    {"symbol": "MTCH", "name": "Match Group, Inc.", "sector": "Communication Services"},
    {"symbol": "NWSA", "name": "News Corporation", "sector": "Communication Services"},
    {"symbol": "OMC", "name": "Omnicom Group Inc.", "sector": "Communication Services"},
    {"symbol": "PARA", "name": "Paramount Skydance Corporation", "sector": "Communication Services"},
    {"symbol": "TTWO", "name": "Take-Two Interactive Software, Inc.", "sector": "Communication Services"},
]

# Always-fresh core set (added 2026-09-08) — the daily batch job (scripts/refresh_universe.py)
# refreshes these first, before spending any remaining FMP quota rotating through the rest
# of the universe. Rationale: with FMP's free-tier daily cap, trying to keep all ~467
# tickers fresh means most of them are stale most of the time and the screener has little
# to show; a small guaranteed-fresh set plus on-demand refresh for anything else (see
# POST /api/stocks/{ticker}/refresh) matches how this app is actually used — a handful of
# people occasionally searching specific tickers, not needing the full index ranked at once.
# Deliberately a fixed, hand-picked list rather than "top N by market cap" or "top N by
# current score" — see the conversation in CLAUDE.md for why those were rejected (circular:
# a ticker that's never refreshed can never earn a score/market-cap figure to enter the set).
CORE_TICKERS: list[str] = ["AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "META", "TSLA", "JPM", "WMT", "XOM"]
